#include "gpio.h"
#include <stddef.h>
#define GPIO_PIN_MAX (15U)
#define GPIO_FIELD_MASK (3UL)
#define GPIO_BIT_MASK (1UL)
static void Gpio_WriteField(volatile uint32_t *reg,uint8_t pin,uint32_t value){const uint32_t shift=(uint32_t)pin*2UL;const uint32_t mask=GPIO_FIELD_MASK<<shift;*reg=(*reg&(~mask))|((value&GPIO_FIELD_MASK)<<shift);}
GpioStatus_t Gpio_WritePin(GpioRegisters_t *gpio,uint8_t pin,GpioLevel_t level){GpioStatus_t status=GPIO_STATUS_OK;if(gpio==NULL){status=GPIO_STATUS_NULL_POINTER;}else if(pin>GPIO_PIN_MAX){status=GPIO_STATUS_INVALID_PIN;}else if((uint32_t)level>(uint32_t)GPIO_LEVEL_HIGH){status=GPIO_STATUS_INVALID_CONFIGURATION;}else{gpio->BSRR=(level==GPIO_LEVEL_HIGH)?(GPIO_BIT_MASK<<pin):(GPIO_BIT_MASK<<((uint32_t)pin+16UL));}return status;}
GpioStatus_t Gpio_InitPin(GpioRegisters_t *gpio,const GpioPinConfig_t *config){GpioStatus_t status=GPIO_STATUS_OK;if((gpio==NULL)||(config==NULL)){status=GPIO_STATUS_NULL_POINTER;}else if(config->pin>GPIO_PIN_MAX){status=GPIO_STATUS_INVALID_PIN;}else if(((uint32_t)config->mode>3UL)||((uint32_t)config->outputType>1UL)||((uint32_t)config->speed>3UL)||((uint32_t)config->pull>2UL)||((uint32_t)config->initialLevel>1UL)){status=GPIO_STATUS_INVALID_CONFIGURATION;}else{const uint32_t mask=GPIO_BIT_MASK<<config->pin;if(config->mode==GPIO_MODE_OUTPUT){status=Gpio_WritePin(gpio,config->pin,config->initialLevel);}if(status==GPIO_STATUS_OK){gpio->OTYPER=(gpio->OTYPER&(~mask))|(((uint32_t)config->outputType&1UL)<<config->pin);Gpio_WriteField(&gpio->OSPEEDR,config->pin,(uint32_t)config->speed);Gpio_WriteField(&gpio->PUPDR,config->pin,(uint32_t)config->pull);Gpio_WriteField(&gpio->MODER,config->pin,(uint32_t)config->mode);}}return status;}
GpioStatus_t Gpio_TogglePin(GpioRegisters_t *gpio,uint8_t pin){GpioStatus_t status=GPIO_STATUS_OK;if(gpio==NULL){status=GPIO_STATUS_NULL_POINTER;}else if(pin>GPIO_PIN_MAX){status=GPIO_STATUS_INVALID_PIN;}else{const GpioLevel_t next=((gpio->ODR&(GPIO_BIT_MASK<<pin))==0UL)?GPIO_LEVEL_HIGH:GPIO_LEVEL_LOW;status=Gpio_WritePin(gpio,pin,next);}return status;}
GpioStatus_t Gpio_ReadPin(const GpioRegisters_t *gpio,uint8_t pin,GpioLevel_t *level){GpioStatus_t status=GPIO_STATUS_OK;if((gpio==NULL)||(level==NULL)){status=GPIO_STATUS_NULL_POINTER;}else if(pin>GPIO_PIN_MAX){status=GPIO_STATUS_INVALID_PIN;}else{*level=((gpio->IDR&(GPIO_BIT_MASK<<pin))!=0UL)?GPIO_LEVEL_HIGH:GPIO_LEVEL_LOW;}return status;}
